######################################################################
# Automatically generated by qmake (2.01a) lör jul 16 10:34:12 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . gui net
INCLUDEPATH += . gui net

LIBS	+= -lSDL2 -lSDL2_net

CONFIG	+= debug

# Input
HEADERS += gui/chat.h gui/login.h net/net.h net/def.h
SOURCES += gui/chat.cpp gui/login.cpp gui/main.cpp net/client.c net/server.c net/def.c
